# Generated by Django 6.0.1 on 2026-06-29 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('service_type', models.CharField(choices=[('barbering', 'Barbering'), ('laundry', 'Laundry'), ('cleaning', 'Cleaning')], max_length=100)),
                ('delivery_type', models.CharField(choices=[('home_delivery', 'Home Delivery'), ('pickup', 'Pickup')], max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('availability', models.BooleanField(default=True)),
                ('working_hours', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'providers',
                'unique_together': {('service_type', 'full_name', 'rating')},
            },
        ),
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('barbering', 'Barbering'), ('laundry', 'Laundry'), ('cleaning', 'Cleaning')], max_length=20)),
                ('experience_years', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('id_document', models.ImageField(upload_to='applications/ids/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_applications',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='provider.provider')),
            ],
            options={
                'db_table': 'services',
                'unique_together': {('provider', 'name', 'price', 'address', 'description', 'description')},
            },
        ),
    ]
