# Generated by Django 6.0.1 on 2026-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_delete_servicetype_alter_provider_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='service_mode',
            field=models.CharField(choices=[('home', 'Home Service'), ('walk_in', 'Walk-in')], default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='service_mode',
            field=models.CharField(choices=[('home', 'Home Service'), ('walk_in', 'Walk-in')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
