# Generated by Django 6.0.1 on 2026-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_normalize_service_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='service_mode',
            field=models.CharField(choices=[('home', 'Home Service'), ('walk_in', 'Walk-in'), ('both', 'Home Service and Walk-in')], max_length=20),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='service_mode',
            field=models.CharField(choices=[('home', 'Home Service'), ('walk_in', 'Walk-in'), ('both', 'Home Service and Walk-in')], max_length=20),
        ),
    ]
