# Generated by Django 6.0.1 on 2026-09-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default="1900-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default="00:00:00"),
            preserve_default=False,
        ),
    ]
